# Generated by Django 4.2.1 on 2023-05-23 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='category',
            field=models.IntegerField(choices=[(0, 'Miscellaneous'), (1, 'Art'), (2, 'Auto Parts'), (3, 'Book'), (4, 'Electronics'), (5, 'Fashion'), (6, 'Gear'), (7, 'Home'), (8, 'Music Instruments'), (9, 'TV/Movie disc'), (10, 'Video Games')], default=0),
        ),
    ]
